### ISSUE TITLE
Redundant memset operation on  coll_tree

### ISSUE THREAD

**Issue by heitaoflower** [exezin/exengine-testing#11]
file: scene.c line:36, 37
memset(s->coll_tree->region.min, 0, sizeof(vec3));
memset(s->coll_tree->region.max, 0, sizeof(vec3));

file octree.c line:15, 16
memset(o->region.min, 0.0f, sizeof(vec3));
memset(o->region.max, 1.0f, sizeof(vec3));

I think default we can set to 0.0 both sides.

**Comment by heitaoflower** [comment]
Hi may I push something if i encountered some issure ?

**Comment by solenum** [comment]
Of course, try to stick to two-space tabs if you can though and use a similar indenting style.

I need to write a contributing.md at some point.

**Comment by heitaoflower** [comment]
Ok, Because I want to use you repo do some personal game.

by the way, Would you explain the code segment as follows.
`negative offset indices
    GLuint offset = 0;
    for (int k=0; k<meshes[i].num_triangles*3; k++) {
      ind[k] -= index_offset;

      if (ind[k] > offset)
        offset = ind[k];
    }
    index_offset += ++offset;`

**Comment by solenum** [comment]
It's to negate the indices so that the indices of each mesh go from 0 to some number, otherwise the indices of the first mesh might be 0 to 100, and then the second mesh 100 to some higher number, which is how they would appear in the iqm file data.  So we offset them to resolve that.

**Comment by heitaoflower** [comment]
@exezin Thank you very much for your explanation.
There is a small question to your engine. I noticed that this project has not been updated for a long time.
What is the plan this year? or what is the roadmap looks like?

**Comment by solenum** [comment]
I've got a small list of things I need to add before I consider my engine complete enough for me to use for real commercial projects.  That list spans stuff like better audio support, frustum culling, finish off the font renderer, and do some general API cleanup.  Most of it is decently easy stuff that wont take a lot of time.  I'm just not hugely motivated to work on it at the moment.

I'm also slowly working on a game with the engine, which means I'm doing a lot of stuff that wont end up in this repo.  Though at the moment I'm mostly doing art stuff and prototyping game mechanics, so it's going to be a little while until I get back to ticking off things from that TODO list.

Edit;  I forgot to add, I also want to merge https://github.com/exezin/exengine-web into this codebase at some point so I don't have to maintain two engines.  I like using the web port for game jams and stuff so that is pretty high on my TODO list.

If you want to discuss these things in real-time consider hopping on the IRC channel ##oodnet on Freenode, I'm frequently talking about engine-dev stuff on there.

**Comment by solenum** [comment]
Update on the TODO list, I'm now tracking that on the "Projects" tab of the repo.

**Comment by heitaoflower** [comment]
Good job, I could help you to port some features, not before one week later.
