### ISSUE TITLE
warning: missing braces around initializer

### ISSUE THREAD

**Issue by subject546** [exezin/exengine-testing#20]
https://github.com/exezin/exengine/blob/7edbadecf833822138e7f4b2e20346b8c46e5728/src/exengine/render/shader.c#L4
https://github.com/exezin/exengine/blob/7edbadecf833822138e7f4b2e20346b8c46e5728/src/exengine/render/shader.c#L5

These two lines generate a compile warning 

> warning: missing braces around initializer [-Wmissing-braces]

I see that you check if the index of the values in the following lines:
https://github.com/exezin/exengine/blob/7edbadecf833822138e7f4b2e20346b8c46e5728/src/exengine/render/shader.c#L21
https://github.com/exezin/exengine/blob/7edbadecf833822138e7f4b2e20346b8c46e5728/src/exengine/render/shader.c#L26

Therefore I don't know if this will break the logic you have here. But I propose the following solution (it seemed equal on my system but maybe I am missing the change)

```
GLint ex_uniform_map[256][256] = {{0}};
GLint ex_uniform_locations[256][256] = {{0}};
```

I'm submitting this as an issue so you can double check if the shader logic is still intact with this change.

**Comment by solenum** [comment]
````
GLint ex_uniform_map[256][256] = {0}; 
````

What actually happens here is that the first element of the array is set to the value in the braces, in this case it would be 0.  After this, the rest of the array is initialized to 0 by default.  If I where to set that value to say, 1.  The first element of the array would be 1 while the rest would again be initialized to 0 by default.

Your solution does indeed remove the warning, without any logic actually changing.

*note that = {0} has been valid since c98, I believe*

**Comment by subject546** [comment]
Ah alright if it's valid c I guess it's fine. And I will close this comment for that.
However one could still argue that the double curly bracket is "more readable", hence why it is probably a compile warning over a compile error.

**Comment by solenum** [comment]
@subject546 feel free to submit a PR though, if not I'll get around to it eventually.  I'm currently focusing on other aspects of the engine.

**Comment by subject546** [comment]
Great I have submitted a pull request for this, this was not really a pressing issue but I will try to help where I can..
